# Generated by Django 2.2 on 2019-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=128, verbose_name='url'),
        ),
    ]
