# Generated by Django 2.2 on 2019-08-26 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190825_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 17, 40, 52, 260361, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
