# Generated by Django 2.2 on 2019-08-26 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190826_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 18, 33, 20, 939290, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
