# Generated by Django 2.2 on 2019-09-08 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20190827_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 23, 27, 12, 451569, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
